import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthSession from "@/components/providers/AuthSession";
import NextUI from "@/components/providers/NextUI";
import Recoil from "@/components/providers/Recoil";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthSession>
          <Recoil>
            <NextUI>{children}</NextUI>
          </Recoil>
        </AuthSession>
      </body>
    </html>
  );
}
